name: Test API Call

on: 
  workflow_dispatch:

jobs:
  post_api_call:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Make API Call
      run: |
        apiUrl="https://empkiranv01.service-now.com/api/sn_devops/v1/devops/tool/test?toolId=66434870c3b54e109b11243599013181&testType=Smoke"
        requestBody='{"toolId": "66434870c3b54e109b11243599013181", "buildNumber": '${{ github.run_number }}' , "workflow": "Test API Call", "repository": "kiranlakhani20/TestTypes-Repo", "name":"Test summary Smoke","duration":0.0,"passedTests":1,"failedTests":1,"skippedTests":1,"blockedTests":1,"totalTests":4,"startTime": "2023-12-14T23:31:31z","finishTime": "2023-12-15T23:31:31z","stageName":"Make API Call","pipelineName":"TestAPICall", "testType": "Smoke", "testSummaries": [{"name": "GitHub Test Summary - smoke","passedTests": 1,"failedTests": 1,"skippedTests": 1,"ignoredTests": 0,"blockedTests": 1,"totalTests": 4,"startTime": "2023-12-14T23:31:31z","endTime": "2023-12-14T23:31:31z","duration": 0.0,"testType": "Smoke", "buildNumber": '${{ github.run_number }}', "buildId": '${{ github.run_id }}' , "attemptNumber" : '${{githubContext.run_attempt}}', "suites": []}] }'
        auth="ZGV2b3BzLmludGVncmF0aW9uLnVzZXI6VGVzdGluZzEh"
        testSummaries='[{"name": "GitHub Test Summary - smoke","passedTests": 1,"failedTests": 1,"skippedTests": 1,"ignoredTests": 0,"blockedTests": 1,"totalTests": 4,"startTime": "2023-12-14T23:31:31z","endTime": "2023-12-14T23:31:31z","duration": 0.0,"testType": "Smoke", "testSummaries": $testSummaries, "suites": []}]'
        authHeader="Basic $auth"
        response=$(curl -X POST -H "Content-Type: application/json" -H "Authorization: $authHeader" -d "$requestBody" $apiUrl)
        exitCode=$?
        
        if [ $exitCode -eq 0 ]; then
          echo "API call successful!"
          echo "Response: $response"
        else
          echo "API call failed!"
          echo "Response: $response"
          exit 1
        fi
